package com.dan.lorebot;

import com.dan.lorebot.commands.CommandAsk;
import com.dan.lorebot.wiki.WikiManager;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import org.apache.logging.log4j.Logger;

@Mod(modid = LoreBot.MODID, name = LoreBot.NAME, version = LoreBot.VERSION, guiFactory = "com.dan.lorebot.config.LoreBotGuiFactory")
public class LoreBot {

    // Unique identifiers for your mod
    public static final String MODID = "lorebot";
    public static final String NAME = "LoreBot AI Assistant";
    public static final String VERSION = "1.0.0";

    public static Logger logger;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        logger = event.getModLog();
        
        // Failsafe: Populate mod metadata manually
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = NAME;
        event.getModMetadata().version = VERSION;
        event.getModMetadata().description = "An AI assistant integrated into Minecraft.";
        event.getModMetadata().authorList.add("Daniel");

        logger.info("==================================================");
        logger.info("Initializing LoreBot's neural systems...");
        logger.info("==================================================");
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        // You can register crafts, items, or blocks here in the future
        WikiManager.init();
        logger.info("LoreBot loaded successfully. Ready to assist.");
    }

    // This event injects our command into the game chat
    @EventHandler
    public void serverStarting(FMLServerStartingEvent event) {
        logger.info("Registering the /ask command...");
        event.registerServerCommand(new CommandAsk());
    }
}